# Generated by Django 6.1 on 2026-08-21 08:55

import railway.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='image',
            field=models.ImageField(null=True, upload_to=railway.models.train_image_path),
        ),
    ]
